Python Web Basics/Exam Preparation/Recipes/recipes_app/recipes_app/rec/urls.py
from django.urls import path
from recipes_app.rec.views import home_page, create_recipe, \
    edit_recipe, delete_recipe, details, create_new, delete_item, edit_btn

urlpatterns = [
    path('', home_page, name='home'),
    path('create/', create_recipe, name='create'),
    path('edit/<int:pk>', edit_recipe, name='edit'),
    path('ed/<int:pk>', edit_btn, name='edit_btn'),
    path('delete/<int:pk>', delete_recipe, name='delete'),
    path('del/<int:pk>', delete_item, name='del'),
    path('details/<int:pk>', details, name='details'),
    path('cc/', create_new),
]

Python Web Basics/Exam Preparation/Recipes/recipes_app/recipes_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes_app.rec.urls'))
]

Python Web Basics/Exam Preparation/Recipes/recipes_app/recipes_app/rec/models.py
from django.db import models

class Recipe(models.Model):
    title = models.CharField(max_length=30)
    image_url = models.URLField()
    description = models.TextField()
    ingredients = models.CharField(max_length=250)
    time = models.IntegerField()

    def substring(self):
        return self.ingredients.split(',')

Python Web Basics/Exam Preparation/Recipes/recipes_app/recipes_app/rec/forms.py
from django import forms


class CreateRecipe(forms.Form):
    title = forms.CharField(max_length=30)
    image_url = forms.URLField()
    description = forms.CharField()
    ingredients = forms.CharField(max_length=250)
    time = forms.IntegerField()

Python Web Basics/Exam Preparation/Recipes/recipes_app/recipes_app/rec/views.py
from django.shortcuts import render, redirect

from recipes_app.rec.models import Recipe


def home_page(request):
    recipes = Recipe.objects.all()
    context = {
        'recipes': recipes,
    }
    return render(request, 'index.html', context)


def create_recipe(request):
    return render(request, 'create.html')


def create_new(request):
    title = request.POST['title']
    image_url = request.POST['image_url']
    description = request.POST['description']
    ingredients = request.POST['ingredients']
    time = request.POST['time']

    form = Recipe(title=title, image_url=image_url, description=description, ingredients=ingredients, time=time)
    form.save()
    return redirect('/')


def edit_recipe(request, pk):
    current = Recipe.objects.get(pk=pk)
    context = {
        'recipe': current,
    }
    return render(request, 'edit.html', context)


def edit_btn(request, pk):
    current = Recipe.objects.get(pk=pk)

    title = request.POST['title']
    image_url = request.POST['image_url']
    description = request.POST['description']
    ingredients = request.POST['ingredients']
    time = request.POST['time']

    form = Recipe(title=title, image_url=image_url, description=description, ingredients=ingredients, time=time)

    if form.title == current.title and \
            form.image_url == current.image_url and\
            form.description == current.description and \
            form.ingredients == current.ingredients and \
            form.time == current.time:
        form.save()
    else:
        current.title = title
        current.image_url = image_url
        current.description = description
        current.ingredients = ingredients
        current.time = time
        current.save()

    return redirect('/')


def delete_recipe(request, pk):
    current = Recipe.objects.get(pk=pk)
    context = {
        'recipe': current
    }
    return render(request, 'delete.html', context)


def delete_item(request, pk):
    current = Recipe.objects.get(pk=pk)
    current.delete()
    return redirect('/')


def details(request, pk):
    context = {
        'recipe': Recipe.objects.get(pk=pk),
    }
    return render(request, 'details.html/', context)

Python Web Basics/Exam Preparation/Recipes/recipes_app/templates/create.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/style.css">
    <title>Recipes</title>
</head>

<body>
     
 <nav>
    <ul>
        <img src="/static/images/chef.png" alt="chef">
        <li class="title"><a href="/">Recipes</a></li>
        <li><a href="{% url 'create' %}">Add Recipe</a></li>
    </ul>
</nav>
    <div class="container">
        
<h1>Create Recipe</h1>
<div class="items-container">
    <div class="item">
        <form method="POST" action="/cc/">
            {% csrf_token %}
            <label for="title">Title</label>
            <input type="text" name="title" maxlength="30" required="" id="id_title">
            <label for="imageURL">Image URL</label>
            <input type="url" name="image_url" maxlength="200" required="" id="id_image_url">
            <label for="description">Description</label>
            <textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>
            <label for="ingredients">Ingredients</label>
            <input type="text" name="ingredients" maxlength="250" required="" id="id_ingredients">
            <label for="time">Time (Minutes)</label>
            <input type="number" name="time" required="" id="id_time">
            <input type="submit" value="Create">
        </form>
    </div>
</div>
    </div>
</body>
</html>

Python Web Basics/Exam Preparation/Recipes/recipes_app/templates/delete.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/style.css">
    <title>Recipes</title>
</head>

<body>
     
 <nav>
    <ul>
        <img src="/static/images/chef.png" alt="chef">
        <li class="title"><a href="/">Recipes</a></li>
        <li><a href="{% url 'create' %}">Add Recipe</a></li>
    </ul>
</nav>
    <div class="container">
        
<h1>Delete Recipe</h1>
<div class="items-container">
    <div class="item">
        <form method="POST" action="{% url 'del' recipe.pk %}">
            {% csrf_token %}
            <label for="title">Title</label>
            <input type="text" name="title" value="{{ recipe.title }}" maxlength="30" disabled="" required="" id="id_title">
            <label for="imageURL">Image URL</label>
            <input type="url" name="image_url" value="{{ recipe.image_url }}" maxlength="200" disabled="" required="" id="id_image_url">
            <label for="description">Description</label>
            <textarea name="description" cols="40" rows="10" disabled="" required="" id="id_description">
            {{ recipe.description }}
            </textarea>
            <label for="ingredients">Ingredients</label>
            <input type="text" name="ingredients" value="{{ recipe.ingredients }}" maxlength="250" disabled="" required="" id="id_ingredients">
            <label for="time">Time (Minutes)</label>
            <input type="number" name="time" value="{{ recipe.time }}" disabled="" required="" id="id_time">
            <input type="submit" class="button delete" value="Delete">
        </form>
    </div>
</div>

    </div>
</body></html>

Python Web Basics/Exam Preparation/Recipes/recipes_app/templates/details.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/style.css">
    <title>Recipes</title>
</head>

<body>
     
 <nav>
    <ul>
        <img src="/static/images/chef.png" alt="chef">
        <li class="title"><a href="/">Recipes</a></li>
        <li><a href="{% url 'create' %}">Add Recipe</a></li>
    </ul>
</nav>
    <div class="container">
        
<h1>Recipe Details</h1>
        <div class="items-container">
            <div class="item">
                <h2>{{ recipe.title}}</h2>
                <img class="detail-img" src="{{ recipe.image_url }}" alt="recipe-image">
                <div class="time">
                    <img src="/static/images/clock.png" alt="clock">
                    <p>{{ recipe.time }}min</p>
                </div>
                <h3>Ingredients</h3>
                <ul>
                    {% for each in recipe.substring %}
                    <li>{{ each }}</li>
                    {% endfor %}
                </ul>
                <h3>How to prepare?</h3>
                <div class="recipe-info-full">
                    {{ recipe.description }}
                </div>
                <div class="buttons-container">
                    <a class="button edit" href="{% url 'edit' recipe.pk %}">Edit</a>
                    <a class="button delete" href="{% url 'delete' recipe.pk %}">Delete</a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Python Web Basics/Exam Preparation/Recipes/recipes_app/templates/edit.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/style.css">
    <title>Recipes</title>
</head>

<body>
     
 <nav>
    <ul>
        <img src="/static/images/chef.png" alt="chef">
        <li class="title"><a href="/">Recipes</a></li>
        <li><a href="{% url 'create' %}">Add Recipe</a></li>
    </ul>
</nav>
    <div class="container">
        
<h1>Edit Recipe</h1>
<div class="items-container">
    <div class="item">
        <form method="POST" action="{% url 'edit_btn' recipe.pk %}">
            {% csrf_token %}
            <label for="title">Title</label>
            <input type="text" name="title" value="{{ recipe.title }}" maxlength="30" required="" id="id_title">
            <label for="imageURL">Image URL</label>
            <input type="url" name="image_url" value="{{ recipe.image_url }}" maxlength="200"  required="" id="id_image_url">
            <label for="description">Description</label>
            <textarea name="description" cols="40" rows="10"  required="" id="id_description">{{ recipe.description }}</textarea>
            <label for="ingredients">Ingredients</label>
            <input type="text" name="ingredients" value="{{ recipe.ingredients }}" maxlength="250"  required="" id="id_ingredients">
            <label for="time">Time (Minutes)</label>
            <input type="number" name="time" value="{{ recipe.time }}" required="" id="id_time">
            <input type="submit" class="button edit" value="Edit">
        </form>
    </div>
</div>

    </div>
</body>
</html>

Python Web Basics/Exam Preparation/Recipes/recipes_app/templates/index.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/style.css">
    <title>Recipes</title>
</head>

<body>
    <nav>
        <ul>
            <img src="/static/images/chef.png" alt="chef">
            <li class="title"><a href="/">Recipes</a></li>
            <li><a href="{% url 'create' %}">Add Recipe</a></li>
        </ul>
    </nav>
    <div class="container">
    <h1>My Recipes</h1>

        {% if not recipes %}
        <h2>There are no recipes.</h2>
        {% endif %}

        <div class="items-container">
            {% for recipe in recipes %}
            <div class="item">
                <h2>{{ recipe.title}}</h2>
                <img class="detail-img" src="{{ recipe.image_url}}" alt="recipe-image">
                <div class="recipe-info">
                    {{ recipe.description }}
                </div>
                <div class="buttons-container">
                    <a class="button detail" href="{% url 'details' recipe.pk %}" >Details</a>
                    <a class="button edit" href="{% url 'edit' recipe.pk %}">Edit</a>
                    <a class="button delete" href="{% url 'delete' recipe.pk %}">Delete</a>
                </div>
            </div>

            {% endfor %}
        </div>
    </div>
</body>
</html>